name: Main

on: [push]

jobs:
  app:
    name: Portfolio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up direnv
        if: github.ref == 'refs/heads/main'
        run: |
          curl -fsSL https://github.com/direnv/direnv/releases/latest/download/direnv.linux-amd64 | sudo tee /usr/local/bin/direnv > /dev/null
          sudo chmod +x /usr/local/bin/direnv
          echo > .env
          direnv allow

      - name: Set up direnv
        run: |
          curl -fsSL https://github.com/direnv/direnv/releases/latest/download/direnv.linux-amd64 | sudo tee /usr/local/bin/direnv > /dev/null
          sudo chmod +x /usr/local/bin/direnv
          echo > .env
          direnv allow

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Set up pnpm
        run: |
          curl -fsSL https://pnpm.js.org/pnpm.js | node - add --global pnpm
          pnpm install --frozen-lockfile

      - name: Check
        run: direnv exec . pnpm check

      - name: Build
        run: direnv exec . pnpm build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          git clone git@github.com:dcecile/dcecile.github.io.git gh-pages
          cd gh-pages
          git rm -rf --ignore-unmatch *
          cp -r ../build/* .
          rm webpack-assets.json
          cp ../README-compiled.md README.md
          cp ../LICENSE.md .
          git add .
          git config --global user.name "Dan Cecile (bot)"
          git config --global user.email "dancecile+bot@gmail.com"
          git commit --allow-empty --message "Compiled from $(cd ..; git rev-parse --short HEAD) :robot:"
          git push
        env:
          ELM_APP_PORTFOLIO_GOOGLE_VERIFICATION: 2FtMQg2XXHmFhtSdaqnKIOSptAm5BF7_ZpejYktGZD8
